version: '3'

services:
    db:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports: 
        - 9000:5432
    web:
        build: .
        image: ecommerce:v1
        volumes: 
            - .:/app
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
        depends_on: 
            - db